name: "PR nginx hello"

on:
  pull_request:
  push:
    branches:
      - master

concurrency: 
  group: build-${{ github.event_name }}
  ### If this is enabled it will cancel current running and start latest
  cancel-in-progress: true

jobs:
   build-and-test-on-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
# Adding sleep time to keep one running and trigger 2nd to check concurrency
      - name: Build and code sim
        run: |
          echo "Starting the code build"
          sleep 30
          echo "Finish --- the code build"
